name: Android APK CI

on:
  push:
    branches: [ main ]
    paths:
      - '**'
  workflow_dispatch:

concurrency:
  group: apk-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Install Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip -O gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.2.1/bin" >> $GITHUB_PATH

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: linkeep-memo-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 14
